#### 1. Create a 3x5 numpy array filled with random numbers from 1 to 10.

#### 1. Ստեղծեք 1-ից 10 պատահական թվերով լցված (3, 5) չափերով numpy array։

In [1]:
import numpy as np

np.random.randint(1, 10, size=15).reshape(3,5)


array([[4, 3, 4, 8, 3],
       [6, 6, 6, 8, 5],
       [9, 1, 3, 9, 6]])

#### 2. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

#### 2. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [2]:
a = np.zeros(10, dtype=int)
a[4] = 3
a


array([0, 0, 0, 0, 3, 0, 0, 0, 0, 0])

#### 3. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

#### 3. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [3]:
np.random.randint(3, 15, size=100000)


array([ 9,  9,  4, ...,  3,  4, 13])

#### 4. Reshape a numpy array of size 6x0 [1, 3, 5, 2, 4, 5] into an array of size 3x2 and then 2x3 without changing the original numpy array.  

#### 4. Վերածեք 6x0 [1, 3, 5, 2, 4, 5] numpy array-ը սկզբում 3x2 այնուհետև 2x3 numpy array-ների առանց սկզբնական numpy array-ը փոփոխելու։

In [4]:

x = np.array([1, 3, 5, 2, 4, 5])
print("Reshape 3x2:\n", np.reshape(x,(3,2)))
print("Reshape 2x3:\n", np.reshape(x,(2,3)))


Reshape 3x2:
 [[1 3]
 [5 2]
 [4 5]]
Reshape 2x3:
 [[1 3 5]
 [2 4 5]]


#### 5. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array.

#### 5. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [5]:
def meanLessEqual5(array: np.ndarray) -> np.ndarray:
    assert(type(array) is np.ndarray)
    while np.mean(array)> 5:
      array = array / 2
    return array

array = np.arange(10, 21)
print(array)
print('mean of original:', np.mean(array))
print(meanLessEqual5(array))
print('mean of reduced:', np.mean(meanLessEqual5(array)))

[10 11 12 13 14 15 16 17 18 19 20]
mean of original: 15.0
[2.5  2.75 3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
mean of reduced: 3.75


#### 6. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an input and returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

#### 6. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [6]:
def returnColumns(array: np.ndarray) -> list:
    assert(array.shape == (5, 4))
    assert(type(array) is np.ndarray)
    array = np.rot90(array, 3)
    return [row[::-1] for row in array]

def returnRows(array: np.ndarray) -> list:
    assert(array.shape == (5, 4))
    assert(type(array) is np.ndarray)
    result = [row for row in array]
    return result

array = np.random.randint(1, 11, (5,4))
print(array)
print("Columns:", returnColumns(array))
print("Rows:", returnRows(array))

[[ 8  3  1  6]
 [ 8  7  4  5]
 [ 3 10  9  6]
 [ 9 10  3 10]
 [10  1  2  1]]
Columns: [array([ 8,  8,  3,  9, 10]), array([ 3,  7, 10, 10,  1]), array([1, 4, 9, 3, 2]), array([ 6,  5,  6, 10,  1])]
Rows: [array([8, 3, 1, 6]), array([8, 7, 4, 5]), array([ 3, 10,  9,  6]), array([ 9, 10,  3, 10]), array([10,  1,  2,  1])]


#### 7. Multiply a 5x3 numpy array by a 3x2 numpy array containing random integer values with some fixed seed. 

#### 7. Ստեղծեք 5x3 ու 3x2 չափանի numpy array-ներ որոնք պարունակում են պատահական integer տիպի արժեքներ ֆիքսված seed-ով։ Գտեք առաջին և երկրորդ  array-ների արտադրյալը։ 

In [7]:
a = np.random.randint(1, 10, (5,3))
b = np.random.randint(1, 10, (3,2))
np.matmul(a, b)

array([[ 77, 111],
       [ 56,  52],
       [ 57,  83],
       [ 56,  54],
       [ 78,  76]])

#### 8. Write a program to sort an array of integers of shape 3x3 first along the columns, the along rows and finally flatten the array so that it becomes an one dimentional array of size 9 and sort the flattened array. 

#### 8. Գրեք ծրագիր որը կսորտավորի ձեր ցանկացած թվերով լցված 3x3 չափանի array-ը սկզբում ըստ սյուների, հետո ըստ տողերի, ապա flatten արեք array-ը դարձնելով այն 9 արժեք պարունակող 1 չափանի array ու սորտավորեք այն։ 

In [8]:
def sortMatrix(array: np.ndarray) -> tuple:
    assert(type(array) is np.ndarray)
    assert(array.shape == (3, 3))
    sorted_by_column = np.sort(array, axis=0)
    sorted_by_rows = np.sort(sorted_by_column, axis=1)
    result = sorted_by_rows.reshape(1,9)
    result = np.sort(result)
    return result 

np.random.seed(1)
array = np.random.randint(1, 11, (3,3))
print(array)
for i in sortMatrix(array):
    print(i, end="\n\n")

[[ 6  9 10]
 [ 6  1  1]
 [ 2  8  7]]
[ 1  1  2  6  6  7  8  9 10]



#### 9. Create a 7 x 7 numpy array of zeros and then "frame" it with a border of ones. Your result should look like this:

#### 9. Ստեղծեք 7 x 7 չափանի, 0-ներով լցված numpy array։ Ավելացրեք numpy array-ին 1-երից բաղկացած “շրջանակ”։ Վերջնական արդյունքը պետք է ունենա հետևյալ տեսքը՝

![image.png](attachment:image.png)

In [9]:
zeros_matsix = np.zeros(36, dtype=int).reshape(6,6)
ones_matrix  = np.ones(49, dtype=int).reshape(7,7)
ones_matrix[1:-1, 1:-1] = 0
print(ones_matrix)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


#### 10. Create the following numpy arrays and calculate the dot product between a and b. Transform the second array if needed.

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։ Transform արեք երկրորդ array-ը եթե կա դրա կարիքը։

$$a = \begin{bmatrix} 1 & 3 \\ 3 & 13 \\ 0 & -1  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [10]:
a = np.array([[1, 3],
              [3, 13],
              [0, -1]])

b = np.array([[1, 1],
              [2, 1],
              [3, -3]])


b = np.transpose(b)
print(b)
np.dot(a, b)


[[ 1  2  3]
 [ 1  1 -3]]


array([[  4,   5,  -6],
       [ 16,  19, -30],
       [ -1,  -1,   3]])